### PR TITLE
Demo for the `@scikit-learn-bot update lock-files` command (legacy)

### PR DESCRIPTION
**Pull request by Charlie-XIAO-qq**
Check the workflow file [here](https://github.com/Charlie-XIAO/github-actions-test/blob/main/.github/workflows/pr-update-lock-files-command.yaml).

- Leave a comment, starting with `@scikit-learn-bot update lock-files`
- Check the commit message if a marker is expected
- Check the commit contents: there should be a new line that is the command to be executed

### CODE REVIEW

**Comment by Charlie-XIAO-qq** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO-qq** [comment]
@scikit-learn-bot update lock-files --select-build doc --skip-build doc_min_dependencies

You can specify the arguments to pass to the `build_tools/update_environments_and_lock_files.py` script in the same line. Everything except the first line will be ignored, so you can add explanations like this.

**Comment by Charlie-XIAO-qq** [comment]
@scikit-learn-bot update lock-files --select-tag main-ci --skip-build doc

Some tags correspond to markers in the commit message. For instance, `main-ci` should add the `[doc build]` marker.

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

Of course maintainers can trigger the workflow as well; not sure if non-maintainers can do so on PRs not made by themselves as well?

**Comment by ROMEEZHOU** [comment]
@scikit-learn-bot update lock-files

It seems like even non-maintainers can trigger the workflow on PRs not made by themselves. Would we want to restrict that?

**Pull request closed without merging**
