### PR TITLE
Demo for the `@scikit-learn-bot update lock-files` command

### PR DESCRIPTION
**Pull request by Charlie-XIAO**

### CODE REVIEW

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files --select-build doc --skip-build doc_min_dependencies

You can specify the arguments to pass to the `build_tools/update_environments_and_lock_files.py` script in the same line. Everything except the first line will be ignored, so you can add explanations like this.

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files --select-tag main-ci --skip-build doc

Some tags correspond to markers in the commit message. For instance, `main-ci` should add the `[doc build]` marker.

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

Passing no arguments means updating all lock files, and thus all commit markers are added as well.

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files --select-build doc --commit-marker "[doc build]"

An additional option `--commit-marker` can be used to add additional markers to the commit message. Quotation marks are needed for tags that contain spaces since the comment is parsed as POSIX shell-like syntax.

**Comment by lesteve** [comment]
@scikit-learn-bot update lock-files --select-tag scipy-dev --commit-marker "[doc build]"

This is to double-check that `--commit-marker` adds a marker (rather than replaces) to the automatically inferred ones and it does.

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

See https://github.com/Charlie-XIAO/github-actions-test/actions/runs/10352876390/job/28654450643. The *I'm doing something malicious in the workflow file...* line is not printed but the *I'm doing something malicious in the Python script...* line is.

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Comment by Charlie-XIAO** [comment]
@scikit-learn-bot update lock-files

**Pull request closed without merging**
