### PR TITLE
Test PR to check what happens when "Allow edits by maintainers" is unticked

### PR DESCRIPTION
**Pull request by lesteve**

### CODE REVIEW

**Comment by lesteve** [comment]
@scikit-learn-bot update lock-files

**Comment by lesteve** [comment]
I guess this makes sense the `git push` fails, see [build log](https://github.com/Charlie-XIAO/github-actions-test/actions/runs/10040496908/job/27746660839?pr=9)

```
Run args=""
[patch-1 fc75c3b] Update lock files
 1 file changed, 1 insertion(+)
 create mode 100644 files/update-lock-files.txt
To https://github.com/lesteve/github-actions-test
 ! [remote rejected] patch-1 -> patch-1 (permission denied)
error: failed to push some refs to 'https://github.com/lesteve/github-actions-test'
Error: Process completed with exit code 1.
```

**Comment by Charlie-XIAO** [comment]
Agreed that this is expected. I guess the only limitation is when making PR from organization's fork where one will not be able to allow edits from maintainers.

**Comment by lesteve** [comment]
Closing since this was only for testing.

**Pull request closed without merging**
